[package]
name = "adpl-ast-lowering"
version.workspace = true
edition.workspace = true

[dependencies]
stacker.workspace = true

adpl-ast.workspace = true
adpl-hir.workspace = true
adpl-util.workspace = true
